# Generated by Django 5.2.17 on 2026-10-06 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def completar_datos_reservas(apps, schema_editor):
    Reserva = apps.get_model('agenda', 'Reserva')
    for reserva in Reserva.objects.select_related('cliente', 'servicio').iterator():
        servicio = reserva.servicio
        cliente = reserva.cliente
        estado_anterior = (reserva.estado or '').strip().lower()
        if estado_anterior in {'cancelada', 'cancelado'}:
            reserva.estado = 'cancelada'
        elif estado_anterior in {'confirmada', 'confirmado'}:
            reserva.estado = 'confirmada'
        elif estado_anterior in {'completada', 'completado'}:
            reserva.estado = 'completada'
        else:
            reserva.estado = 'pendiente'
        if reserva.origen and 'cliente' in reserva.origen.lower():
            reserva.origen = 'cliente'
        else:
            reserva.origen = 'manual'
        reserva.servicio_nombre = servicio.nombre if servicio else 'Servicio eliminado'
        reserva.duracion_minutos = servicio.duracion_minutos if servicio else 30
        if cliente:
            reserva.cliente_nombre = ' '.join(
                part for part in (
                    cliente.nombre,
                    cliente.apellido_paterno,
                    cliente.apellido_materno,
                ) if part
            )
            reserva.cliente_email = cliente.email
            reserva.cliente_telefono = cliente.telefono
        reserva.save(update_fields=[
            'estado',
            'origen',
            'servicio_nombre',
            'duracion_minutos',
            'cliente_nombre',
            'cliente_email',
            'cliente_telefono',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizonte_meses', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'verbose_name': 'configuración de agenda',
                'verbose_name_plural': 'configuración de agenda',
            },
        ),
        migrations.CreateModel(
            name='DiaCerrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'día cerrado',
                'verbose_name_plural': 'días cerrados',
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'ordering': ['dia_semana', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha_hora']},
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='descanso_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='descanso_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_especifica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reserva',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicio_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(completar_datos_reservas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='disponibilidad',
            name='dia_semana',
            field=models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='origen',
            field=models.CharField(blank=True, choices=[('manual', 'Agendada por administración'), ('cliente', 'Agendada por cliente')], default='manual', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.servicioagenda'),
        ),
        migrations.AlterField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='agenda.servicioagenda'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='agenda.servicioagenda'),
        ),
    ]
