# Generated by Django 5.2.17 on 2026-10-06 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_servicioagenda_configuracionagenda_diacerrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.servicioagenda'),
        ),
        migrations.AlterField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='agenda.servicioagenda'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='agenda.servicioagenda'),
        ),
    ]
