# Generated by Django 5.2.17 on 2026-10-06 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_disponibilidad_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='agenda.categoriaagenda')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesional_categoria',
                'constraints': [models.UniqueConstraint(fields=('profesional', 'categoria'), name='uniq_profesional_categoria')],
            },
        ),
    ]
