# Generated by Django 5.2.17 on 2026-10-06 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def disable_weekly_availability(apps, schema_editor):
    disponibilidad = apps.get_model('agenda', 'Disponibilidad')
    disponibilidad.objects.filter(fecha_especifica__isnull=True).update(activo=False)
    disponibilidad.objects.filter(profesional__isnull=True).update(activo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_categoriaagenda_profesionalcategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(disable_weekly_availability, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CambioDisponibilidadPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bloque_inicio', models.TimeField()),
                ('bloque_fin', models.TimeField()),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_disponibilidad_pendientes', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_pendientes', to='agenda.servicioagenda')),
            ],
        ),
        migrations.DeleteModel(
            name='ConfiguracionAgenda',
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_suspension',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='respuesta_suspension',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('suspendida', 'Suspendida: esperando respuesta'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cambio_disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='agenda.cambiodisponibilidadpendiente'),
        ),
        migrations.AddConstraint(
            model_name='cambiodisponibilidadpendiente',
            constraint=models.UniqueConstraint(fields=('fecha', 'servicio', 'profesional', 'bloque_inicio'), name='uniq_cambio_disponibilidad_bloque'),
        ),
    ]
