# Generated by Django 5.2.17 on 2026-10-10 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0005_cambiodisponibilidadpendiente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('abono', 'Pagado parcialmente')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(default='Pago ficticio', max_length=40)),
                ('estado', models.CharField(default='aprobado', max_length=20)),
                ('transaccion_id', models.CharField(max_length=36, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_simulados', to='carrito.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=20)),
                ('producto_id_catalogo', models.PositiveBigIntegerField(blank=True, null=True)),
                ('servicio_id_catalogo', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalidad_pago', models.CharField(choices=[('completo', 'Pago completo'), ('abono', 'Abono de $5.000'), ('no_aplica', 'No aplica')], max_length=20)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='agenda.reserva')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.pedido')),
            ],
        ),
    ]
