# Generated by Django 5.2.17 on 2026-10-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('producto_id', models.PositiveBigIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('vence_en', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['vence_en'], name='carrito_reserva_vence_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'producto_id'), name='uniq_reserva_producto_carrito')],
            },
        ),
    ]
