# Generated by Django 5.2.17 on 2026-10-03 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias_condiciones', models.TextField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ficha_cliente',
            },
        ),
        migrations.CreateModel(
            name='AlertaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('atendida', models.BooleanField(default=False)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='fichas.fichacliente')),
            ],
            options={
                'db_table': 'alerta_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='HistorialAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateTimeField()),
                ('notas_sesion', models.TextField()),
                ('tratamiento_recomendado', models.TextField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='fichas.fichacliente')),
            ],
            options={
                'db_table': 'historial_atencion',
            },
        ),
        migrations.CreateModel(
            name='MaterialCambiosCito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_citos', to='fichas.fichacliente')),
            ],
            options={
                'db_table': 'material_cambios_cito',
            },
        ),
    ]
