# Generated by Django 5.2.17 on 2026-10-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(default='Aprobado', max_length=50)),
                ('transaccion_id', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
