# Generated by Django 5.2.17 on 2026-10-10 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cambiodisponibilidadpendiente_and_more'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita', 'Cita próxima'), ('seguimiento', 'Seguimiento posterior')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_enviados', to='agenda.reserva')),
            ],
            options={
                'db_table': 'recordatorio_enviado',
                'ordering': ['-enviado_en'],
                'constraints': [models.UniqueConstraint(fields=('reserva', 'tipo'), name='uniq_recordatorio_reserva_tipo')],
            },
        ),
    ]
