# Generated by Django 5.2.17 on 2026-10-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_cambiodisponibilidadpendiente_and_more'),
        ('notificaciones', '0002_recordatorioenviado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordatorioenviado',
            name='uniq_recordatorio_reserva_tipo',
        ),
        migrations.AddField(
            model_name='recordatorioenviado',
            name='desfase',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='recordatorioenviado',
            constraint=models.UniqueConstraint(fields=('reserva', 'tipo', 'desfase'), name='uniq_recordatorio_reserva_tipo_desfase'),
        ),
    ]
